Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -48,8 +48,11 @@ jobs:
         id: check-tag
         with: 
           tag: ${{ env.newVersion }}
-      - run: echo ${{ env.newVersion }} " exists!"
-        if: steps.check-tag.outputs.exists == 'true' 
+      - name: Fail if tag already exists
+        if: steps.check-tag.outputs.exists == 'true'
+        run: |
+          echo "❌ The tag '${{ env.newVersion }}' already exists. Aborting the workflow."
+          exit 1
       - name: Release snapshot
         id: release-snapshot
         uses: actions/create-release@latest
